/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProgram_(Program_ *p) {} //abstract class

void PrintAbsyn::visitProgram(Program *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListDecl(p->listdecl_);
  _i_ = 0; visitListStatement(p->liststatement_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListDecl(ListDecl *listdecl)
{
  iterListDecl(listdecl->begin(), listdecl->end());
}

void PrintAbsyn::iterListDecl(ListDecl::const_iterator i, ListDecl::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListDecl(i+1, j);
  }
}

void PrintAbsyn::visitDecl(Decl *p) {} //abstract class

void PrintAbsyn::visitDeclaration(Declaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("declare");
  visitIdent(p->ident_);
  render("as");
  _i_ = 0; p->typereference_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeReference(TypeReference *p) {} //abstract class

void PrintAbsyn::visitNothingType(NothingType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Nothing");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBoolType(BoolType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Boolean");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIntegerType(IntegerType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Integer");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDoubleType(DoubleType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Double");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStringType(StringType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("String");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAutoType(AutoType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Auto");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunctionDeclType(FunctionDeclType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcdecl_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunctionDefType(FunctionDefType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcdefn_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayType(ArrayType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->typereference_->accept(this);
  render("[]");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitClassType(ClassType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->classdecl_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitUserType(UserType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitClassDecl(ClassDecl *p) {} //abstract class

void PrintAbsyn::visitClassDeclaration(ClassDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("class");
  _i_ = 0; p->extends_->accept(this);
  _i_ = 0; p->statics_->accept(this);
  render('{');
  _i_ = 0; p->cbody_->accept(this);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExtends(Extends *p) {} //abstract class

void PrintAbsyn::visitExtendsEmpty(ExtendsEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExtendsList(ExtendsList *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');
  visitIdent(p->ident_);
  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListIdent(ListIdent *listident)
{
  iterListIdent(listident->begin(), listident->end());
}

void PrintAbsyn::iterListIdent(ListIdent::const_iterator i, ListIdent::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    visitIdent(*i);
  }
  else
  { /* cons */
    visitIdent(*i); render(','); iterListIdent(i+1, j);
  }
}

void PrintAbsyn::visitFieldDef(FieldDef *p) {} //abstract class

void PrintAbsyn::visitFieldDeclaration(FieldDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->typereference_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFieldDefinition(FieldDefinition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFieldDefinitionAsc(FieldDefinitionAsc *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->typereference_->accept(this);
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatics(Statics *p) {} //abstract class

void PrintAbsyn::visitStaticsEmpty(StaticsEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStaticsBody(StaticsBody *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('(');
  _i_ = 0; visitListFieldDef(p->listfielddef_);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListFieldDef(ListFieldDef *listfielddef)
{
  iterListFieldDef(listfielddef->begin(), listfielddef->end());
}

void PrintAbsyn::iterListFieldDef(ListFieldDef::const_iterator i, ListFieldDef::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListFieldDef(i+1, j);
  }
}

void PrintAbsyn::visitCBody(CBody *p) {} //abstract class

void PrintAbsyn::visitClassBody(ClassBody *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListFieldDef(p->listfielddef_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncDecl(FuncDecl *p) {} //abstract class

void PrintAbsyn::visitFunctionDeclaration(FunctionDeclaration *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcrange_->accept(this);
  render("->");
  _i_ = 0; p->funcdomain_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncDefn(FuncDefn *p) {} //abstract class

void PrintAbsyn::visitFunctionDefinition(FunctionDefinition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcrangenamed_->accept(this);
  render("->");
  _i_ = 0; p->funcdomain_->accept(this);
  _i_ = 0; p->body__->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncDomain(FuncDomain *p) {} //abstract class

void PrintAbsyn::visitFunctionDomain(FunctionDomain *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->typereference_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncRange(FuncRange *p) {} //abstract class

void PrintAbsyn::visitFunctionRangeSingle(FunctionRangeSingle *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->typereference_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunctionRangeMultiple(FunctionRangeMultiple *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('(');
  _i_ = 0; p->typereference_->accept(this);
  render(',');
  _i_ = 0; visitListTypeReference(p->listtypereference_);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListTypeReference(ListTypeReference *listtypereference)
{
  iterListTypeReference(listtypereference->begin(), listtypereference->end());
}

void PrintAbsyn::iterListTypeReference(ListTypeReference::const_iterator i, ListTypeReference::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListTypeReference(i+1, j);
  }
}

void PrintAbsyn::visitFuncParam(FuncParam *p) {} //abstract class

void PrintAbsyn::visitFunctionParameter(FunctionParameter *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->typereference_->accept(this);
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncRangeNamed(FuncRangeNamed *p) {} //abstract class

void PrintAbsyn::visitFunctionRangeSingleNamed(FunctionRangeSingleNamed *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funcparam_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunctionRangeMultipleNamed(FunctionRangeMultipleNamed *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('(');
  _i_ = 0; visitListFuncParam(p->listfuncparam_);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListFuncParam(ListFuncParam *listfuncparam)
{
  iterListFuncParam(listfuncparam->begin(), listfuncparam->end());
}

void PrintAbsyn::iterListFuncParam(ListFuncParam::const_iterator i, ListFuncParam::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListFuncParam(i+1, j);
  }
}

void PrintAbsyn::visitStatement(Statement *p) {} //abstract class

void PrintAbsyn::visitStatementVarDecl(StatementVarDecl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("let");
  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->typereference_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementVarDef(StatementVarDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("let");
  visitIdent(p->ident_);
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementVarDefAsc(StatementVarDefAsc *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("let");
  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->typereference_->accept(this);
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementAssignment(StatementAssignment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expression_->accept(this);
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementIf(StatementIf *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->statementif__->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementWhile(StatementWhile *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("while");
  _i_ = 0; p->expression_->accept(this);
  _i_ = 0; p->body__->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementFor(StatementFor *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("for");
  visitIdent(p->ident_);
  render("in");
  _i_ = 0; p->rangeexpr_->accept(this);
  _i_ = 0; p->body__->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementReturnNone(StatementReturnNone *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("return");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementReturnValue(StatementReturnValue *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("return");
  _i_ = 0; p->expression_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementFunctionCall(StatementFunctionCall *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->funccall_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatementIf_(StatementIf_ *p) {} //abstract class

void PrintAbsyn::visitIfStatement(IfStatement *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expression_->accept(this);
  _i_ = 0; p->body__->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIfElseIfStatement(IfElseIfStatement *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expression_->accept(this);
  _i_ = 0; p->body__->accept(this);
  render("else");
  _i_ = 0; p->statementif__->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIfElseStatement(IfElseStatement *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expression_->accept(this);
  _i_ = 0; p->body__1->accept(this);
  render("else");
  _i_ = 0; p->body__2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBody_(Body_ *p) {} //abstract class

void PrintAbsyn::visitBody(Body *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListStatement(p->liststatement_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValue(Value *p) {} //abstract class

void PrintAbsyn::visitValueArrowed(ValueArrowed *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("<-");
  _i_ = 0; p->expression_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValueBraced(ValueBraced *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; p->expression_->accept(this);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListStatement(ListStatement *liststatement)
{
  iterListStatement(liststatement->begin(), liststatement->end());
}

void PrintAbsyn::iterListStatement(ListStatement::const_iterator i, ListStatement::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListStatement(i+1, j);
  }
}

void PrintAbsyn::visitExpression(Expression *p) {} //abstract class

void PrintAbsyn::visitMethodReference(MethodReference *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expression_->accept(this);
  render("::");
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationalEquals(RelationalEquals *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  _i_ = 5; p->expression_1->accept(this);
  render('=');
  _i_ = 6; p->expression_2->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationalNotEquals(RelationalNotEquals *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  _i_ = 5; p->expression_1->accept(this);
  render("!=");
  _i_ = 6; p->expression_2->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationalLess(RelationalLess *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  _i_ = 5; p->expression_1->accept(this);
  render('<');
  _i_ = 6; p->expression_2->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationalGreater(RelationalGreater *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  _i_ = 5; p->expression_1->accept(this);
  render('>');
  _i_ = 6; p->expression_2->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationalLessOrEqual(RelationalLessOrEqual *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  _i_ = 5; p->expression_1->accept(this);
  render("<=");
  _i_ = 6; p->expression_2->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRelationalGreaterOrEqual(RelationalGreaterOrEqual *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  _i_ = 5; p->expression_1->accept(this);
  render(">=");
  _i_ = 6; p->expression_2->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArithmeticSum(ArithmeticSum *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  _i_ = 6; p->expression_1->accept(this);
  render('+');
  _i_ = 7; p->expression_2->accept(this);

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArithmeticDifference(ArithmeticDifference *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  _i_ = 6; p->expression_1->accept(this);
  render('-');
  _i_ = 7; p->expression_2->accept(this);

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArithmeticProduct(ArithmeticProduct *p)
{
  int oldi = _i_;
  if (oldi > 7) render(_L_PAREN);

  _i_ = 7; p->expression_1->accept(this);
  render('*');
  _i_ = 8; p->expression_2->accept(this);

  if (oldi > 7) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArithmeticQuotient(ArithmeticQuotient *p)
{
  int oldi = _i_;
  if (oldi > 7) render(_L_PAREN);

  _i_ = 7; p->expression_1->accept(this);
  render('/');
  _i_ = 8; p->expression_2->accept(this);

  if (oldi > 7) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArithmeticModulus(ArithmeticModulus *p)
{
  int oldi = _i_;
  if (oldi > 7) render(_L_PAREN);

  _i_ = 7; p->expression_1->accept(this);
  render('%');
  _i_ = 8; p->expression_2->accept(this);

  if (oldi > 7) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArithmeticExponentiation(ArithmeticExponentiation *p)
{
  int oldi = _i_;
  if (oldi > 8) render(_L_PAREN);

  _i_ = 8; p->expression_1->accept(this);
  render('^');
  _i_ = 9; p->expression_2->accept(this);

  if (oldi > 8) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicalUnaryNot(LogicalUnaryNot *p)
{
  int oldi = _i_;
  if (oldi > 4) render(_L_PAREN);

  render("not");
  _i_ = 3; p->expression_->accept(this);

  if (oldi > 4) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicalConjunction(LogicalConjunction *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 3; p->expression_1->accept(this);
  render("and");
  _i_ = 4; p->expression_2->accept(this);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicalDisjunction(LogicalDisjunction *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 2; p->expression_1->accept(this);
  render("or");
  _i_ = 3; p->expression_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicalExclusiveDisjunction(LogicalExclusiveDisjunction *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 2; p->expression_1->accept(this);
  render("xor");
  _i_ = 3; p->expression_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicalImplication(LogicalImplication *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  _i_ = 1; p->expression_1->accept(this);
  render("=>");
  _i_ = 2; p->expression_2->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLogicalEquivalence(LogicalEquivalence *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  _i_ = 1; p->expression_1->accept(this);
  render("<=>");
  _i_ = 2; p->expression_2->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitUnaryHashCode(UnaryHashCode *p)
{
  int oldi = _i_;
  if (oldi > 9) render(_L_PAREN);

  render('#');
  _i_ = 10; p->expression_->accept(this);

  if (oldi > 9) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitUnaryMinus(UnaryMinus *p)
{
  int oldi = _i_;
  if (oldi > 9) render(_L_PAREN);

  render('-');
  _i_ = 10; p->expression_->accept(this);

  if (oldi > 9) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTrueTerm(TrueTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  render("true");

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFalseTerm(FalseTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  render("false");

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEmptyTerm(EmptyTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  render("empty");

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStringTerm(StringTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  visitString(p->string_);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIntegerTerm(IntegerTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDoubleTerm(DoubleTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariableReferenceTerm(VariableReferenceTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayReferenceTerm(ArrayReferenceTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  _i_ = 10; p->expression_1->accept(this);
  render('[');
  _i_ = 0; p->expression_2->accept(this);
  render(']');

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFieldReferenceTerm(FieldReferenceTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  _i_ = 10; p->expression_->accept(this);
  render('.');
  visitIdent(p->ident_);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunctionCallExpr(FunctionCallExpr *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  _i_ = 0; p->funccall_->accept(this);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayInitializer(ArrayInitializer *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  render('[');
  _i_ = 0; visitListExpression(p->listexpression_);
  render(']');

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRangeExpressionTerm(RangeExpressionTerm *p)
{
  int oldi = _i_;
  if (oldi > 10) render(_L_PAREN);

  _i_ = 0; p->rangeexpr_->accept(this);

  if (oldi > 10) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFuncCall(FuncCall *p) {} //abstract class

void PrintAbsyn::visitFunctionCall(FunctionCall *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 10; p->expression_->accept(this);
  render('(');
  _i_ = 0; visitListExpression(p->listexpression_);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListExpression(ListExpression *listexpression)
{
  iterListExpression(listexpression->begin(), listexpression->end());
}

void PrintAbsyn::iterListExpression(ListExpression::const_iterator i, ListExpression::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListExpression(i+1, j);
  }
}

void PrintAbsyn::visitRangeExpr(RangeExpr *p) {} //abstract class

void PrintAbsyn::visitRangeExpression(RangeExpression *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->unsteppedrangeexpression_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSteppedRangeExpression(SteppedRangeExpression *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->unsteppedrangeexpression_->accept(this);
  render(':');
  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitUnsteppedRangeExpression(UnsteppedRangeExpression *p) {} //abstract class

void PrintAbsyn::visitOpenRange(OpenRange *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('(');
  _i_ = 0; p->rangebody__->accept(this);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitClosedRange(ClosedRange *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('[');
  _i_ = 0; p->rangebody__->accept(this);
  render(']');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLeftClosedRightOpenedRange(LeftClosedRightOpenedRange *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('[');
  _i_ = 0; p->rangebody__->accept(this);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLeftOpenedRightClosedRange(LeftOpenedRightClosedRange *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('(');
  _i_ = 0; p->rangebody__->accept(this);
  render(']');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRangeBody_(RangeBody_ *p) {} //abstract class

void PrintAbsyn::visitRangeBody(RangeBody *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_1);
  render(';');
  visitInteger(p->integer_2);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProgram_(Program_ *p) {} //abstract class

void ShowAbsyn::visitProgram(Program *p)
{
  bufAppend('(');
  bufAppend("Program");
  bufAppend(' ');
  bufAppend('[');
  if (p->listdecl_)  p->listdecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListDecl(ListDecl *listdecl)
{
  for (ListDecl::const_iterator i = listdecl->begin() ; i != listdecl->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listdecl->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitDecl(Decl *p) {} //abstract class

void ShowAbsyn::visitDeclaration(Declaration *p)
{
  bufAppend('(');
  bufAppend("Declaration");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTypeReference(TypeReference *p) {} //abstract class

void ShowAbsyn::visitNothingType(NothingType *p)
{
  bufAppend("NothingType");
}
void ShowAbsyn::visitBoolType(BoolType *p)
{
  bufAppend("BoolType");
}
void ShowAbsyn::visitIntegerType(IntegerType *p)
{
  bufAppend("IntegerType");
}
void ShowAbsyn::visitDoubleType(DoubleType *p)
{
  bufAppend("DoubleType");
}
void ShowAbsyn::visitStringType(StringType *p)
{
  bufAppend("StringType");
}
void ShowAbsyn::visitAutoType(AutoType *p)
{
  bufAppend("AutoType");
}
void ShowAbsyn::visitFunctionDeclType(FunctionDeclType *p)
{
  bufAppend('(');
  bufAppend("FunctionDeclType");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcdecl_)  p->funcdecl_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFunctionDefType(FunctionDefType *p)
{
  bufAppend('(');
  bufAppend("FunctionDefType");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcdefn_)  p->funcdefn_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitArrayType(ArrayType *p)
{
  bufAppend('(');
  bufAppend("ArrayType");
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitClassType(ClassType *p)
{
  bufAppend('(');
  bufAppend("ClassType");
  bufAppend(' ');
  bufAppend('[');
  if (p->classdecl_)  p->classdecl_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitUserType(UserType *p)
{
  bufAppend('(');
  bufAppend("UserType");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitClassDecl(ClassDecl *p) {} //abstract class

void ShowAbsyn::visitClassDeclaration(ClassDeclaration *p)
{
  bufAppend('(');
  bufAppend("ClassDeclaration");
  bufAppend(' ');
  bufAppend('[');
  if (p->extends_)  p->extends_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->statics_)  p->statics_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->cbody_)  p->cbody_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitExtends(Extends *p) {} //abstract class

void ShowAbsyn::visitExtendsEmpty(ExtendsEmpty *p)
{
  bufAppend("ExtendsEmpty");
}
void ShowAbsyn::visitExtendsList(ExtendsList *p)
{
  bufAppend('(');
  bufAppend("ExtendsList");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListIdent(ListIdent *listident)
{
  for (ListIdent::const_iterator i = listident->begin() ; i != listident->end() ; ++i)
  {
    visitIdent(*i) ;
    if (i != listident->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitFieldDef(FieldDef *p) {} //abstract class

void ShowAbsyn::visitFieldDeclaration(FieldDeclaration *p)
{
  bufAppend('(');
  bufAppend("FieldDeclaration");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFieldDefinition(FieldDefinition *p)
{
  bufAppend('(');
  bufAppend("FieldDefinition");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFieldDefinitionAsc(FieldDefinitionAsc *p)
{
  bufAppend('(');
  bufAppend("FieldDefinitionAsc");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatics(Statics *p) {} //abstract class

void ShowAbsyn::visitStaticsEmpty(StaticsEmpty *p)
{
  bufAppend("StaticsEmpty");
}
void ShowAbsyn::visitStaticsBody(StaticsBody *p)
{
  bufAppend('(');
  bufAppend("StaticsBody");
  bufAppend(' ');
  bufAppend('[');
  if (p->listfielddef_)  p->listfielddef_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListFieldDef(ListFieldDef *listfielddef)
{
  for (ListFieldDef::const_iterator i = listfielddef->begin() ; i != listfielddef->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listfielddef->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitCBody(CBody *p) {} //abstract class

void ShowAbsyn::visitClassBody(ClassBody *p)
{
  bufAppend('(');
  bufAppend("ClassBody");
  bufAppend(' ');
  bufAppend('[');
  if (p->listfielddef_)  p->listfielddef_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFuncDecl(FuncDecl *p) {} //abstract class

void ShowAbsyn::visitFunctionDeclaration(FunctionDeclaration *p)
{
  bufAppend('(');
  bufAppend("FunctionDeclaration");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcrange_)  p->funcrange_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->funcdomain_)  p->funcdomain_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFuncDefn(FuncDefn *p) {} //abstract class

void ShowAbsyn::visitFunctionDefinition(FunctionDefinition *p)
{
  bufAppend('(');
  bufAppend("FunctionDefinition");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcrangenamed_)  p->funcrangenamed_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->funcdomain_)  p->funcdomain_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->body__)  p->body__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFuncDomain(FuncDomain *p) {} //abstract class

void ShowAbsyn::visitFunctionDomain(FunctionDomain *p)
{
  bufAppend('(');
  bufAppend("FunctionDomain");
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFuncRange(FuncRange *p) {} //abstract class

void ShowAbsyn::visitFunctionRangeSingle(FunctionRangeSingle *p)
{
  bufAppend('(');
  bufAppend("FunctionRangeSingle");
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFunctionRangeMultiple(FunctionRangeMultiple *p)
{
  bufAppend('(');
  bufAppend("FunctionRangeMultiple");
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listtypereference_)  p->listtypereference_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListTypeReference(ListTypeReference *listtypereference)
{
  for (ListTypeReference::const_iterator i = listtypereference->begin() ; i != listtypereference->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtypereference->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitFuncParam(FuncParam *p) {} //abstract class

void ShowAbsyn::visitFunctionParameter(FunctionParameter *p)
{
  bufAppend('(');
  bufAppend("FunctionParameter");
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitFuncRangeNamed(FuncRangeNamed *p) {} //abstract class

void ShowAbsyn::visitFunctionRangeSingleNamed(FunctionRangeSingleNamed *p)
{
  bufAppend('(');
  bufAppend("FunctionRangeSingleNamed");
  bufAppend(' ');
  bufAppend('[');
  if (p->funcparam_)  p->funcparam_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFunctionRangeMultipleNamed(FunctionRangeMultipleNamed *p)
{
  bufAppend('(');
  bufAppend("FunctionRangeMultipleNamed");
  bufAppend(' ');
  bufAppend('[');
  if (p->listfuncparam_)  p->listfuncparam_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListFuncParam(ListFuncParam *listfuncparam)
{
  for (ListFuncParam::const_iterator i = listfuncparam->begin() ; i != listfuncparam->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listfuncparam->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitStatement(Statement *p) {} //abstract class

void ShowAbsyn::visitStatementVarDecl(StatementVarDecl *p)
{
  bufAppend('(');
  bufAppend("StatementVarDecl");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementVarDef(StatementVarDef *p)
{
  bufAppend('(');
  bufAppend("StatementVarDef");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementVarDefAsc(StatementVarDefAsc *p)
{
  bufAppend('(');
  bufAppend("StatementVarDefAsc");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->typereference_)  p->typereference_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementAssignment(StatementAssignment *p)
{
  bufAppend('(');
  bufAppend("StatementAssignment");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementIf(StatementIf *p)
{
  bufAppend('(');
  bufAppend("StatementIf");
  bufAppend(' ');
  bufAppend('[');
  if (p->statementif__)  p->statementif__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementWhile(StatementWhile *p)
{
  bufAppend('(');
  bufAppend("StatementWhile");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->body__)  p->body__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementFor(StatementFor *p)
{
  bufAppend('(');
  bufAppend("StatementFor");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->rangeexpr_)  p->rangeexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->body__)  p->body__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementReturnNone(StatementReturnNone *p)
{
  bufAppend("StatementReturnNone");
}
void ShowAbsyn::visitStatementReturnValue(StatementReturnValue *p)
{
  bufAppend('(');
  bufAppend("StatementReturnValue");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementFunctionCall(StatementFunctionCall *p)
{
  bufAppend('(');
  bufAppend("StatementFunctionCall");
  bufAppend(' ');
  bufAppend('[');
  if (p->funccall_)  p->funccall_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatementIf_(StatementIf_ *p) {} //abstract class

void ShowAbsyn::visitIfStatement(IfStatement *p)
{
  bufAppend('(');
  bufAppend("IfStatement");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->body__)  p->body__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIfElseIfStatement(IfElseIfStatement *p)
{
  bufAppend('(');
  bufAppend("IfElseIfStatement");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->body__)  p->body__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->statementif__)  p->statementif__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIfElseStatement(IfElseStatement *p)
{
  bufAppend('(');
  bufAppend("IfElseStatement");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->body__1->accept(this);
  bufAppend(' ');
  p->body__2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitBody_(Body_ *p) {} //abstract class

void ShowAbsyn::visitBody(Body *p)
{
  bufAppend('(');
  bufAppend("Body");
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitValue(Value *p) {} //abstract class

void ShowAbsyn::visitValueArrowed(ValueArrowed *p)
{
  bufAppend('(');
  bufAppend("ValueArrowed");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitValueBraced(ValueBraced *p)
{
  bufAppend('(');
  bufAppend("ValueBraced");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListStatement(ListStatement *liststatement)
{
  for (ListStatement::const_iterator i = liststatement->begin() ; i != liststatement->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != liststatement->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitExpression(Expression *p) {} //abstract class

void ShowAbsyn::visitMethodReference(MethodReference *p)
{
  bufAppend('(');
  bufAppend("MethodReference");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitRelationalEquals(RelationalEquals *p)
{
  bufAppend('(');
  bufAppend("RelationalEquals");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRelationalNotEquals(RelationalNotEquals *p)
{
  bufAppend('(');
  bufAppend("RelationalNotEquals");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRelationalLess(RelationalLess *p)
{
  bufAppend('(');
  bufAppend("RelationalLess");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRelationalGreater(RelationalGreater *p)
{
  bufAppend('(');
  bufAppend("RelationalGreater");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRelationalLessOrEqual(RelationalLessOrEqual *p)
{
  bufAppend('(');
  bufAppend("RelationalLessOrEqual");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRelationalGreaterOrEqual(RelationalGreaterOrEqual *p)
{
  bufAppend('(');
  bufAppend("RelationalGreaterOrEqual");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitArithmeticSum(ArithmeticSum *p)
{
  bufAppend('(');
  bufAppend("ArithmeticSum");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitArithmeticDifference(ArithmeticDifference *p)
{
  bufAppend('(');
  bufAppend("ArithmeticDifference");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitArithmeticProduct(ArithmeticProduct *p)
{
  bufAppend('(');
  bufAppend("ArithmeticProduct");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitArithmeticQuotient(ArithmeticQuotient *p)
{
  bufAppend('(');
  bufAppend("ArithmeticQuotient");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitArithmeticModulus(ArithmeticModulus *p)
{
  bufAppend('(');
  bufAppend("ArithmeticModulus");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitArithmeticExponentiation(ArithmeticExponentiation *p)
{
  bufAppend('(');
  bufAppend("ArithmeticExponentiation");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicalUnaryNot(LogicalUnaryNot *p)
{
  bufAppend('(');
  bufAppend("LogicalUnaryNot");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitLogicalConjunction(LogicalConjunction *p)
{
  bufAppend('(');
  bufAppend("LogicalConjunction");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicalDisjunction(LogicalDisjunction *p)
{
  bufAppend('(');
  bufAppend("LogicalDisjunction");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicalExclusiveDisjunction(LogicalExclusiveDisjunction *p)
{
  bufAppend('(');
  bufAppend("LogicalExclusiveDisjunction");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicalImplication(LogicalImplication *p)
{
  bufAppend('(');
  bufAppend("LogicalImplication");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLogicalEquivalence(LogicalEquivalence *p)
{
  bufAppend('(');
  bufAppend("LogicalEquivalence");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitUnaryHashCode(UnaryHashCode *p)
{
  bufAppend('(');
  bufAppend("UnaryHashCode");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitUnaryMinus(UnaryMinus *p)
{
  bufAppend('(');
  bufAppend("UnaryMinus");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTrueTerm(TrueTerm *p)
{
  bufAppend("TrueTerm");
}
void ShowAbsyn::visitFalseTerm(FalseTerm *p)
{
  bufAppend("FalseTerm");
}
void ShowAbsyn::visitEmptyTerm(EmptyTerm *p)
{
  bufAppend("EmptyTerm");
}
void ShowAbsyn::visitStringTerm(StringTerm *p)
{
  bufAppend('(');
  bufAppend("StringTerm");
  bufAppend(' ');
  visitString(p->string_);
  bufAppend(')');
}
void ShowAbsyn::visitIntegerTerm(IntegerTerm *p)
{
  bufAppend('(');
  bufAppend("IntegerTerm");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitDoubleTerm(DoubleTerm *p)
{
  bufAppend('(');
  bufAppend("DoubleTerm");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitVariableReferenceTerm(VariableReferenceTerm *p)
{
  bufAppend('(');
  bufAppend("VariableReferenceTerm");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitArrayReferenceTerm(ArrayReferenceTerm *p)
{
  bufAppend('(');
  bufAppend("ArrayReferenceTerm");
  bufAppend(' ');
  p->expression_1->accept(this);
  bufAppend(' ');
  p->expression_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitFieldReferenceTerm(FieldReferenceTerm *p)
{
  bufAppend('(');
  bufAppend("FieldReferenceTerm");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitFunctionCallExpr(FunctionCallExpr *p)
{
  bufAppend('(');
  bufAppend("FunctionCallExpr");
  bufAppend(' ');
  bufAppend('[');
  if (p->funccall_)  p->funccall_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitArrayInitializer(ArrayInitializer *p)
{
  bufAppend('(');
  bufAppend("ArrayInitializer");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRangeExpressionTerm(RangeExpressionTerm *p)
{
  bufAppend('(');
  bufAppend("RangeExpressionTerm");
  bufAppend(' ');
  bufAppend('[');
  if (p->rangeexpr_)  p->rangeexpr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFuncCall(FuncCall *p) {} //abstract class

void ShowAbsyn::visitFunctionCall(FunctionCall *p)
{
  bufAppend('(');
  bufAppend("FunctionCall");
  bufAppend(' ');
  bufAppend('[');
  if (p->expression_)  p->expression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpression_)  p->listexpression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListExpression(ListExpression *listexpression)
{
  for (ListExpression::const_iterator i = listexpression->begin() ; i != listexpression->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listexpression->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitRangeExpr(RangeExpr *p) {} //abstract class

void ShowAbsyn::visitRangeExpression(RangeExpression *p)
{
  bufAppend('(');
  bufAppend("RangeExpression");
  bufAppend(' ');
  bufAppend('[');
  if (p->unsteppedrangeexpression_)  p->unsteppedrangeexpression_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitSteppedRangeExpression(SteppedRangeExpression *p)
{
  bufAppend('(');
  bufAppend("SteppedRangeExpression");
  bufAppend(' ');
  bufAppend('[');
  if (p->unsteppedrangeexpression_)  p->unsteppedrangeexpression_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitUnsteppedRangeExpression(UnsteppedRangeExpression *p) {} //abstract class

void ShowAbsyn::visitOpenRange(OpenRange *p)
{
  bufAppend('(');
  bufAppend("OpenRange");
  bufAppend(' ');
  bufAppend('[');
  if (p->rangebody__)  p->rangebody__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitClosedRange(ClosedRange *p)
{
  bufAppend('(');
  bufAppend("ClosedRange");
  bufAppend(' ');
  bufAppend('[');
  if (p->rangebody__)  p->rangebody__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitLeftClosedRightOpenedRange(LeftClosedRightOpenedRange *p)
{
  bufAppend('(');
  bufAppend("LeftClosedRightOpenedRange");
  bufAppend(' ');
  bufAppend('[');
  if (p->rangebody__)  p->rangebody__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitLeftOpenedRightClosedRange(LeftOpenedRightClosedRange *p)
{
  bufAppend('(');
  bufAppend("LeftOpenedRightClosedRange");
  bufAppend(' ');
  bufAppend('[');
  if (p->rangebody__)  p->rangebody__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRangeBody_(RangeBody_ *p) {} //abstract class

void ShowAbsyn::visitRangeBody(RangeBody *p)
{
  bufAppend('(');
  bufAppend("RangeBody");
  bufAppend(' ');
  visitInteger(p->integer_1);
  bufAppend(' ');
  visitInteger(p->integer_2);
  bufAppend(')');
}
void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


