/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitExp(Exp *t) {} //abstract class

void Skeleton::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->exp_1) e_add->exp_1->accept(this);
  if (e_add->exp_2) e_add->exp_2->accept(this);

}

void Skeleton::visitESub(ESub *e_sub)
{
  /* Code For ESub Goes Here */

  if (e_sub->exp_1) e_sub->exp_1->accept(this);
  if (e_sub->exp_2) e_sub->exp_2->accept(this);

}

void Skeleton::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->exp_1) e_mul->exp_1->accept(this);
  if (e_mul->exp_2) e_mul->exp_2->accept(this);

}

void Skeleton::visitEDiv(EDiv *e_div)
{
  /* Code For EDiv Goes Here */

  if (e_div->exp_1) e_div->exp_1->accept(this);
  if (e_div->exp_2) e_div->exp_2->accept(this);

}

void Skeleton::visitEInt(EInt *e_int)
{
  /* Code For EInt Goes Here */

  visitInteger(e_int->integer_);

}



void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



